name: Build and Deploy

on:
  push:
    branches:
      - develop

env:
  ECR-REPOSITORY: repo_cicd_app

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: awssyncsession
          role-to-assume: ${{secrets.AWS_IAM_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build the image
        id: image-builded
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          TAG: ${{github.sha}}
        run: |
          docker build -t $REGISTRY/$ECR_REPOSITORY:$TAG .
          docker push $REGISTRY/$ECR_REPOSITORY:$TAG

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Replace image in the ECS Task definition
  #       id: task-definition
  #       uses: aws-actions/amazon-ecs-render-task-definition@v1
  #       with:
          

